### ISSUE TITLE
not able to visualize overlapping objects(bounding boxes)

### ISSUE THREAD

**Issue by suyogkute** [wkentaro/imgviz#56] opened 2023-05-15 12:09 UTC

**Comment by suyogkute** [comment] 2023-05-16 05:04
maskviz_1 = imgviz.instances2rgb(img, masks= np.moveaxis(out[0]["masks"],-1,0), labels=out[0]["class_ids"], captions=np.array(["double_stitch_0.98","textured_panel_0.91","short_heel_0.86"]))

if you see the first label is not visualized, I guess its overlapping for sure. let me know if I am wrong

![image](https://github.com/wkentaro/imgviz/assets/25390594/918a98f0-449b-43aa-bec5-c53c230f772b)

**Comment by wkentaro** [comment] 2023-09-12 07:53
@suyogkute I don't think they are overlapping since we should be able to tell that by the mask or bounding box. (Or are these exactly the same mask?)

**Comment by wkentaro** [comment] 2023-10-03 14:18
Closing for now. Please reopen if it reproduces.

**Closed by wkentaro** 2023-10-03 14:18 UTC
